# Longboxes development commands.
# Run `just` with no arguments to see this list.

# Auto-load .env into the recipe environment so MATCH_WORKER_REPLICAS
# (and any other variables) reach the shell that runs ``docker
# compose ... --scale worker=$N`` below. Without this, just runs each
# recipe in a clean shell that has no ``.env`` knowledge.
set dotenv-load := true

default:
    @just --list

# Bring up the stack in the background.
#
# Match worker count comes from ``MATCH_WORKER_REPLICAS`` in ``.env``
# (defaults to 1). Passed via ``--scale`` so it works on every Docker
# Compose version — the ``deploy.replicas`` value in
# ``docker-compose.yml`` documents the same intent but is only fully
# honoured by swarm, so we don't rely on it.
up:
    docker compose up -d --build --scale worker=${MATCH_WORKER_REPLICAS:-1}

# Same but tail logs in the foreground.
up-logs:
    docker compose up --build --scale worker=${MATCH_WORKER_REPLICAS:-1}

# Stop the stack (keeps volumes)
down:
    docker compose down

# Tail logs; optionally pass a service name (web, worker, db, redis)
logs service="":
    docker compose logs -f {{service}}

# Run database migrations to head
migrate:
    docker compose exec web alembic upgrade head

# Generate a new autogenerated migration (e.g. `just makemigration add-users-table`)
makemigration name:
    docker compose exec web alembic revision --autogenerate -m "{{name}}"

# Roll back the most recent migration
downgrade:
    docker compose exec web alembic downgrade -1

# Open a bash shell in the web container
shell:
    docker compose exec web bash

# Open psql against the running database
psql:
    docker compose exec db psql -U longboxes -d longboxes

# Enqueue a no-op job to verify the queue works end-to-end
test-job:
    docker compose exec web python -c "from redis import Redis; from rq import Queue; from app.config import settings; q = Queue(connection=Redis.from_url(settings.redis_url)); job = q.enqueue('app.jobs.noop.noop', 'phase-0 test'); print(f'Enqueued job: {job.id}')"

# Enqueue a library scan immediately
scan:
    docker compose exec web python -c "from redis import Redis; from app.config import settings; from app.jobs.scan import enqueue_scan_now; print('Scan queued:', enqueue_scan_now(Redis.from_url(settings.redis_url)))"

# Print configured library paths (from app_settings)
library-paths:
    docker compose exec db psql -U longboxes -d longboxes -At -c "SELECT value FROM app_settings WHERE key='library_paths';"

# Add (or refresh) a ComicVine volume by CV ID. Requires API key set in /admin.
# Example: just add-volume 18166
add-volume cv_id:
    docker compose exec web python -m app.scripts.add_volume {{cv_id}}

# Print every issue in a volume with its hydration state and arc credits.
# Diagnostic for the volume page's story-arc stripes — if every hydrated issue
# reports `arcs: (none)`, CV has no arc data for this volume.
# Example: just inspect-arcs 18166
inspect-arcs volume_cv_id:
    docker compose exec web python -m app.scripts.inspect_volume_arcs {{volume_cv_id}}

# Enqueue match_file for every file without a resolved match (no row, unmatched, or pending).
# Same as the "Match all unmatched" button on /admin.
match-all:
    docker compose exec web python -c "from app.jobs.match_file import enqueue_match_all_unmatched; print('Queued:', enqueue_match_all_unmatched())"

# Run the test suite (uses a separate `longboxes_test` database, auto-created)
test:
    docker compose exec web pytest

# Create a user from the command line. Use `role=admin` or `role=viewer`.
# Example: `just create-user alice somepass viewer`
create-user username password role="viewer":
    docker compose exec web python -m app.scripts.create_user {{username}} {{password}} {{role}}

# Reset an existing user's password. Username must already exist;
# for net-new accounts use create-user instead.
# Example: `just reset-password alice newpass123`
reset-password username password:
    docker compose exec web python -m app.scripts.reset_password {{username}} {{password}}

# List every user account (username, role, created-at). Password
# hashes are never printed. Useful when recovering an account whose
# username you've forgotten.
list-users:
    docker compose exec web python -m app.scripts.list_users

# Lint
lint:
    docker compose exec web ruff check .

# Format (in-place)
fmt:
    docker compose exec web ruff format .

# Rebuild images from scratch
rebuild:
    docker compose build --no-cache

# Stop the stack and wipe all volumes (destructive)
nuke:
    docker compose down -v
